library(Capr)

# Generated by jsonToCapr()
# Source JSON: /Users/michaelconlin/hades/cohort_arbs.json

# --- concept sets ---
csArbs <- cs(
  descendants(
    1308842,
    1317640,
    1346686,
    1347384,
    1351557,
    1367500,
    40226742,
    40235485
  ),
  name = "ARBs"
)
csGenetichereditaryrcca <- cs(
  descendants(4263213, 380839),
  37399456,
  37160584,
  descendants(4110719),
  35622838,
  4240212,
  37396489,
  name = "GeneticHereditaryRCCa"
)
csEsrdArbstudy <- cs(
  descendants(37395652, 443611, 193782),
  name = "ESRD_ARBstudy"
)
csTransplantStatusArbstudy <- cs(
  descendants(42537741),
  name = "Transplant_status_ARBstudy"
)
csHypertensionArbstudy <- cs(
  descendants(316866),
  name = "Hypertension_ARBstudy"
)
csRenalCellCarcinoma <- cs(
  descendants(45765451, 45773365, 37116954),
  198985,
  name = "renal cell carcinoma"
)
# create the attrition object to pass to the cohort function
attritionObj <- attrition(
  expressionLimit = "First", # limit the entry events to the first per person
  # "Age > 18" = withAll(age(gt(18L))), # include only those over 18 years old at the time of cohort entry
  "No prior RCCa" = withAll(exactly(
    0L,
    conditionOccurrence(csRenalCellCarcinoma), # exclude those with prior renal cell carcinoma
    duringInterval(
      startWindow = eventStarts(-Inf, Inf, index = "startDate"), #
      restrictVisit = FALSE,
      ignoreObservationPeriod = FALSE
    )
  )),
  "No familial/genetic risk of Rcca" = withAll(exactly(
    0L,
    conditionOccurrence(csGenetichereditaryrcca),
    duringInterval(
      startWindow = eventStarts(-Inf, Inf, index = "startDate"),
      restrictVisit = FALSE,
      ignoreObservationPeriod = FALSE
    )
  )),
  "No ESRD" = withAll(exactly(
    0L,
    conditionOccurrence(csEsrdArbstudy),
    duringInterval(
      startWindow = eventStarts(-Inf, 0L, index = "startDate"),
      restrictVisit = FALSE,
      ignoreObservationPeriod = FALSE
    )
  )),
  "No Transplant" = withAll(exactly(
    0L,
    conditionOccurrence(csTransplantStatusArbstudy),
    duringInterval(
      startWindow = eventStarts(-Inf, 0L, index = "startDate"),
      restrictVisit = FALSE,
      ignoreObservationPeriod = FALSE
    )
  ))
)

# --- cohort ---
cohortDef <- cohort(
  entry = entry(
    drugEra(csArbs), # eraLength(gt(60L))),
    observationWindow = continuousObservation(priorDays = 365L, postDays = 0L),
    primaryCriteriaLimit = "First",
    qualifiedLimit = "First"
  ),
  attrition = attritionObj,
  exit = exit(
    endStrategy = observationExit()
  ) #,
  #era = era(eraDays = 0L)
)
